# Generated by Django 2.2.2 on 2019-06-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=30)),
                ('razao_social', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(max_length=50, unique=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='Cnpj')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, verbose_name='Inscrição estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='Inscrição municipal')),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('site', models.CharField(max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('endereco', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_medidor', models.IntegerField(default=0)),
                ('text', models.TextField(max_length=200)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='areas.Empresas')),
            ],
        ),
    ]
