# Generated by Django 2.2.2 on 2019-06-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_r', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumo_s', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumo_t', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='areas.Areas')),
            ],
        ),
    ]
